name: Sync Releases

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次，具体时间间隔可根据需求调整
  workflow_dispatch: # 手动触发

jobs:
  sync-releases:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Fetch latest release from upstream
      id: fetch-latest-release
      run: |
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/lobehub/lobe-chat/releases/latest)
        TAG_NAME=$(echo $LATEST_RELEASE | jq -r .tag_name)
        RELEASE_NAME=$(echo $LATEST_RELEASE | jq -r .name)
        RELEASE_BODY=$(echo $LATEST_RELEASE | jq -r .body)
        echo "::set-output name=tag_name::$TAG_NAME"
        echo "::set-output name=release_name::$RELEASE_NAME"
        echo "::set-output name=release_body::$RELEASE_BODY"

    - name: Fetch latest release from this repository
      id: fetch-current-release
      run: |
        CURRENT_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
        CURRENT_TAG_NAME=$(echo $CURRENT_RELEASE | jq -r .tag_name)
        echo "::set-output name=tag_name::$CURRENT_TAG_NAME"
      continue-on-error: true # 如果没有发布过release，则忽略错误

    - name: Compare versions and create release if needed
      if: steps.fetch-latest-release.outputs.tag_name != steps.fetch-current-release.outputs.tag_name
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.fetch-latest-release.outputs.tag_name }}
        release_name: ${{ steps.fetch-latest-release.outputs.release_name }}
        body: ${{ steps.fetch-latest-release.outputs.release_body }}
        draft: false
        prerelease: false
