name: Sync Upstream Release

on:
  workflow_dispatch:  # 添加这个事件
  release:
    types: [published]

jobs:
  sync-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要完整的历史记录以便于版本标签的处理

      - name: Set up Git
        run: |
          git config --global user.name "cnlihz"
          git config --global user.email "931462664@qq.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/lobehub/lobe-chat.git

      - name: Save current local tags
        id: save_tags
        run: |
          current_tags=$(git tag | grep -v - | sort -V | tail -n 1)
          echo "current_tags=${current_tags}" >> $GITHUB_ENV

      - name: Fetch upstream releases
        run: |
          # 删除本地的冲突标签
          for tag in $(git tag); do
            if git ls-remote --tags upstream | grep -q "refs/tags/$tag"; then
              git tag -d "$tag"
            fi
          done

          # 获取上游标签
          git fetch upstream --tags

      - name: Check for new upstream release
        id: check_release
        run: |
          # 获取最新的上游版本标签
          latest_upstream_release=$(git tag | grep -v - | sort -V | tail -n 1)
          echo "latest_upstream_release=${latest_upstream_release}" >> $GITHUB_ENV

      - name: Create a new release
        if: env.latest_upstream_release != '' && env.current_tags != env.latest_upstream_release
        run: |
          # 创建新版本
          git tag -a "$latest_upstream_release" -m "Release $latest_upstream_release from upstream"
          git push origin "$latest_upstream_release"
